### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zavalacl/wk3_proj3#1]
Very nice attention to detail in the presentation! The background with the custom font looks really sharp. The generated pages [do seem to be returning some HTML errors](http://validator.w3.org/check?uri=https%3A%2F%2Fpure-journey-8994.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0) though. Can you try to resolve those and update the repo? Let me know if you need any help.

**Comment by zavalacl** [comment]
I believe they are fixed now :)

**Comment by chrisvfritz** [comment]
It is much better, but I do still see an unmatched `</p>` that's throwing an error in `index1.html`. Sorry to be nitpicky! Fix that and it'll be done. :smiley:

**Comment by zavalacl** [comment]
Ok I decided to get rid of the tag, it should be fixed now :)

**Comment by chrisvfritz** [comment]
:+1: Wonderful! This isn't something you have to fix here, but a few resources to help you in future projects:

### Getting rid of `.DS_Store` clutter

OS X automatically generates hidden `.DS_Store` files and by default, Git will include them your commits. To get rid of this clutter in our Git repos, you can [check out this link](http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository).

### Unused `index.html`

It looks like there's an unused `index.html` file in your views folder. Since it's no longer needed, it's best to just delete it to keep our project from becoming cluttered.

If you you did delete it locally and are surprised that it's still on GitHub, then try running this line before your next commit:

``` bash
git add -A .
```

That will add not only file additions and modifications, but also file deletions. I know, it's strange that you need a special parameter for this, but you do.
